name: Golang Tests
on: [pull_request]
jobs:
  build:
    name: Golang Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Test with the Go CLI
      run: go test ./...
