name: Templ Generation
on: [pull_request]
jobs:
  build:
    name: Templ Generator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Templ Generator
      run: templ generate

    - name: Check for changes
      run: if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then exit 1; fi
