name: Templ Format
on: [pull_request]
jobs:
  build:
    name: Templ Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Templ
      run: go install github.com/a-h/templ/cmd/templ@v0.2.598

    - name: Templ Formatter
      run: templ fmt .

    - name: Check for changes
      run: |
        if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
          echo "Error: Templ files need to be formatted. Run 'templ fmt .' using v0.2.598."
          exit 1
        fi
